# Generated by Django 6.0.7 on 2026-08-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasim'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('delivering', 'Yetkazilmoqda'), ('completed', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=50, verbose_name='Holat'),
        ),
    ]
